config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "control#index"

  post "/function", to: "control#function"
  post "/variable", to: "control#variable"

  resource :users, only: [:new, :create]
  get   "/user", to: "users#show"
  patch "/user", to: "users#update"
  put   "/user", to: "users#update"
end

app/models/core.rb
class Core < ActiveRecord::Base
  belongs_to :user

  validates :user, :name, :core_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :validatable

  has_many :cores,
    dependent:  :destroy,
    inverse_of: :user
  accepts_nested_attributes_for :cores, reject_if: :all_blank

  validates :access_token, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/control_controller.rb
class ControlController < ApplicationController
  def index
  end

  def function
    value = core.function(name, argument)
    render json: {response: value}
  rescue => e
    render json: {response: e.to_s}
  end

  def variable
    binding.pry
    value = core.variable(name)
    render json: {response: value}
  rescue => e
    render json: {response: e.to_s}
  end

  private

  %w(core_id name argument).each do |field|
    define_method field do
      params[:api_call][field]
    end
  end

  def access_token
    if current_user
      current_user.try(:access_token)
    else
      params[:api_call][:access_token]
    end
  end

  def timeout
    if current_user
      current_user.try(:timeout)
    else
      10.seconds
    end
  end

  def core
    @core ||= begin
      RubySpark.configuration do |config|
        config.access_token = access_token
        config.timeout      = timeout
      end

      RubySpark::Core.new(core_id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :assign_user, only: [:show, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(:user, @user)
      flash[:notice] = "Welcome!"
      redirect_to root_url
    else
      flash.now[:alert] = "There was an issue with that"
      render :new
    end
  end

  def show
  end

  def update
    if @user.update_attributes(user_params)
      flash[:notice] = "Account updated!"
      redirect_to root_url
    else
      flash.now[:alert] = "There was an issue with that"
      render :show
    end
  end

  private

  def assign_user
    @user = current_user
  end

  def user_params
    params[:user].permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def core_options
    current_user.cores.map do |core|
      [core.name, core.core_id]
    end
  end
end

app/views/control/index.html.erb
<div class="well col-md-6">
  <h2>Call Function</h2>
  <br>

  <%= form_for :api_call, remote: true, url: '/function', html: {id: "function_call"} do |f| %>
    <%= render "users/particle_authentication_fields", f: f %>

    <br>

    <%= f.label :name, "Function Name" %>
    <%= f.text_field :name, class: "form-control" %>

    <br>

    <%= f.label :argument, "Function Argument" %>
    <%= f.text_field :argument, class: "form-control" %>

    <br>
    <br>

    <div class="input-group">
      <span class="input-group-btn">
        <%= f.submit "Execute", class: 'btn btn-primary' %>
      </span>
      <%= f.text_field :results, placeholder: "Results...", class: "form-control", disabled: true, id: "function_call_results" %>
    </div>
  <% end %>
</div>

<div class="well col-md-6">
  <h2>Retrieve Variable</h2>
  <br>

  <%= form_for :api_call, remote: true, url: '/variable', html: {id: "retrieve_variable"} do |f| %>
    <%= render "users/particle_authentication_fields", f: f %>

    <br>

    <%= f.label :name, "Variable Name" %>
    <%= f.text_field :name, class: "form-control" %>

    <br>
    <br>

    <div class="input-group">
      <span class="input-group-btn">
        <%= f.submit "Execute", class: 'btn btn-primary' %>
      </span>
      <%= f.text_field :results, placeholder: "Results...", class: "form-control", disabled: true, id: "retrieve_variable_results" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Interfacer</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= render "shared/header" %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</div>

<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/shared/_core_fields.html.erb
<%= f.fields_for :cores do |g| %>
  <div class="well">
    <%= g.label :name %>
    <%= g.text_field :name, class: "form-control" %>
    <%= g.label :core_id, "Core ID" %>
    <%= g.text_field :core_id, class: "form-control" %>
  <br>
  <%= g.link_to_remove "Remove this Core" %>
  </div>
<% end %>
<%= f.link_to_add "Add a Core", :cores %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Interfacer", root_url, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to "Log In",  new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_users_path %></li>
        <% else %>
          <li><%= link_to "Account", user_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/users/_particle_authentication_fields.html.erb
<% if current_user %>
  <%= f.label :core_id, "Core" %>
  <%= f.select :core_id, core_options, class: "form-control" %>
  <br>
<% else %>
  <%= f.label :access_token, "Access Token" %>
  <%= f.text_field :access_token, class: "form-control" %>

  <br>

  <%= f.label :core_id, "Core ID" %>
  <%= f.text_field :core_id, class: "form-control" %>
<% end %>

app/views/users/new.html.erb
<h2>Sign up</h2>

<div class="well col-md-6">
  <h2>Edit Account</h2>
  <br>

  <%= nested_form_for @user do |f| %>
    <div><%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, class: "form-control" %></div>

    <div><%= f.label :password %><br />
      <%= f.password_field :password, autocomplete: "off", class: "form-control" %></div>

    <div><%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %></div>

    <div><%= f.label :access_token %><br />
    <%= f.text_field :access_token, class: "form-control" %></div>

    <br>

    <%= render "shared/core_fields", f: f %>

    <br>
    <br>

    <%= f.submit "Sign up", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="well col-md-6">
  <h2>Edit Account</h2>
  <br>

  <%= nested_form_for @user do |f| %>
    <%= f.label :access_token, "Access Token" %>
    <%= f.text_field :access_token, class: "form-control" %>

    <%= f.label :timeout, "Particle API Timeout" %>
    <%= f.number_field :timeout, class: "form-control" %>

    <br>

    <%= render "shared/core_fields", f: f %>

    <br>
    <br>

    <%= f.submit "Update", class: 'btn btn-primary' %>
    <%= link_to "Cancel", root_url, class: 'btn btn-default' %>
  <% end %>
</div>